# Use a local cache; only files in the project directory can be cached.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - pip install nox

# Run all of the test activities using Python 3.8.
tests-38:
  image: python:3.8-slim
  script:
    - nox

# Run all of the test activities using Python 3.9.
tests-39:
  image: python:3.9-slim
  script:
    - nox

# Run all of the test activities using Python 3.10.
tests-310:
  image: python:3.10-slim
  script:
    - nox

# Run all of the test activities using Python 3.11.
tests-311:
  image: python:3.11-slim
  coverage: '/^TOTAL.+?(\d+\%)$/'
  script:
    - nox
