# Use a local cache; only files in the project directory can be cached.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

# Run all of the test activities in tox.ini using Python 3.8.
tox-38:
  image: python:3.8-slim
  script:
    - pip install tox
    - tox

# Run all of the test activities in tox.ini using Python 3.9.
tox-39:
  image: python:3.9-slim
  script:
    - pip install tox
    - tox

# Run all of the test activities in tox.ini using Python 3.10.
tox-310:
  image: python:3.10-slim
  script:
    - pip install tox
    - tox

# Run all of the test activities in tox.ini using Python 3.11.
tox-311:
  image: python:3.11-slim
  coverage: '/^TOTAL.+?(\d+\%)$/'
  script:
    - pip install tox
    - tox
